feat: implement router CreateUser
HenriqueCursino/gateway pull request #4
Opened 2022-09-29 17:18 UTC by HenriqueCursino

2022-09-29 17:30 UTC, GuilhermeSembeneli commented on .vscode/launch.json
> +{
acredito que esse arquivo subiu sem querer

2022-09-29 17:30 UTC, GuilhermeSembeneli commented on common/env.go
>  func GetEnviroment(envName string) string {
seria interessante voltar as validações para dar um Panic caso nao encontre a variável de ambiente

2022-09-29 17:36 UTC, GuilhermeSembeneli commented on controller/controller.go
> +// função para receber os métodos da interface
Seria interessante remover o comentario ou utilizar o goDoc.

// NewController receive methods about core user

2022-09-29 17:36 UTC, GuilhermeSembeneli commented on controller/controller.go
> +		serv,
Seria interessante chamar de service mesmo, em vez de ser

2022-09-29 17:36 UTC, GuilhermeSembeneli commented on controller/controller.go
> +	c.ShouldBindJSON(&userRequest)
seria interessante validar se deu erro para adicionar o json

2022-09-29 17:37 UTC, GuilhermeSembeneli commented on controller/controller.go
> +	errors.IsEmptyError(err)
aqui temos que retornar um status Code error caso tenha acontecido algum erro.

2022-09-29 17:37 UTC, GuilhermeSembeneli commented on dto/user.go
> +	FullName string `json:"full_name"`
Seria interessante utilizar o `binding="required"` para deixar o campo como obrigatório

2022-09-29 17:38 UTC, GuilhermeSembeneli commented on dto/user.go
> +	FullName string `gorm:"size:30"`
Seria interessante evitar o uso do gorm na dato e levar isso para model.

2022-09-29 17:38 UTC, GuilhermeSembeneli commented on repository/repository.go
> +	CreateUser(user *dto.UserCreat) error
acredito que aqui faltou o E em creat

2022-09-29 17:39 UTC, GuilhermeSembeneli commented on repository/repository.go
> +	if err := repo.db.Table("users").Create(&user).Error; err != nil {
Seria interessante armazenar essa tabela em uma constante

2022-09-29 17:39 UTC, GuilhermeSembeneli commented on router/router.go
>  	router.Run(":8080")
Seria interessante deixar essa porta em uma variável de ambiente.

2022-09-29 17:41 UTC, GuilhermeSembeneli commented on service/service.go
> +	documentInt := tools.TreatDoc(userRequest.Cpf)
Seria  interessante pensar em um nome melhor para essa função, outro ponto é interessante gravar no banco de dados um campo chamado document em vez de cpf e cnpj

2022-09-29 17:43 UTC, PedroSMarcal requested changes

2022-09-29 17:43 UTC, PedroSMarcal commented on .vscode/launch.json
> +{
colocar no .gitignore esta pasta .vscode

2022-09-29 17:43 UTC, PedroSMarcal commented on controller/controller.go
> +func (ctl controller) PostUser(c *gin.Context) {
Uma Recomendação seria deixar apenas o c aqui para definir o nome da assinatura, e ponterizar

2022-09-29 17:43 UTC, PedroSMarcal commented on controller/controller.go
> +	err := ctl.serv.UserService(userRequest)
Caso retornar um erro, seria interessante tu retornar ao usuario uma bad request, ou algo do genero, para indicar da forma como está sempre retornara statusOK

2022-09-29 17:43 UTC, PedroSMarcal commented on dto/user.go
> +type UserCreat struct {
UserCreate*

2022-09-29 17:43 UTC, PedroSMarcal commented on repository/repository.go
> +func (repo repository) CreateUser(user *dto.UserCreat) error {
a mesma coisa de ponterizar a assinatura

2022-09-29 17:43 UTC, PedroSMarcal commented on router/router.go
> +	repo := repository.NewRepository(db)
No caso tu já instanciando as dependencias aqui direto na sua repository, seria viavel ter um arquivos apenas com as dependencies, e apenas reotrnar a parte da controller

2022-09-29 17:43 UTC, PedroSMarcal commented on tools/tools.go
> +	documentInt, _ := convertStrToInt(documentUnmasked)
Qual a necessidade de retornar um erro se ira skipar ele

2022-10-04 14:21 UTC, PedroSMarcal approved these changes

2022-10-04 14:21 UTC, PedroSMarcal commented on controller/controller.go
> +	userRequest := dto.UserRequest{}
Uma Sugestão é usar o new(UserRequest), o objeto já é iniciado ponterizado desta forma, não precisando ser desreferenciado todo uso

2022-10-04 14:21 UTC, PedroSMarcal commented on main.go
> +	if err != nil {
Neste caso, tu já iniciar o Load das envs na função abaixo

2022-10-04 14:21 UTC, PedroSMarcal commented on repository/repository.go
> +type Repository interface {
Poderiamos colocar como IRepository

2022-10-04 14:21 UTC, PedroSMarcal commented on service/service.go
> +		Hash:     uuid.New().String(),
Maybe we should split in a diferent function the option to create a new Hash

2022-10-04 14:21 UTC, PedroSMarcal commented on service/service.go
> +	claims["exp"] = time.Now().Add(time.Minute * time.Duration(oneDay)).Unix() // minutes
This function time.Now().Add(), if used in another place, set as function splited

2022-10-04 14:39 UTC, merged